name: RetroCam
options:
  bundleIdPrefix: com.kreatix
  xcodeVersion: "15.4"
targets:
  RetroCam:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - build.yml
